[SERVICE]
    Flush        5
    Daemon       Off
    Log_Level    info
    Parsers_File parsers.conf

[INPUT]
    Name              tail
    Path              /var/log/nginx/access.log
    Tag               nginx.access
    Parser            nginx
    Refresh_Interval  5

[INPUT]
    Name              tail
    Path              /var/log/nginx/error.log
    Tag               nginx.error
    Parser            nginx_error
    Refresh_Interval  5

[INPUT]
    Name              tail
    Path              /var/log/php-fpm/*.log
    Tag               php.fpm
    Refresh_Interval  5

[INPUT]
    Name              tail
    Path              /var/log/mysql/*.log
    Tag               mariadb
    Refresh_Interval  5

[INPUT]
    Name              tail
    Path              /var/log/php-fpm/*.log
    Tag               php.fpm
    Parser            php_fpm
    Refresh_Interval  5

[INPUT]
    Name              tail
    Path              /var/log/mysql/*.log
    Tag               mariadb
    Parser            mariadb
    Refresh_Interval  5

[FILTER]
    Name    modify
    Match   nginx.access
    Add     log_type nginx_access

[FILTER]
    Name    modify
    Match   nginx.error
    Add     log_type nginx_error

[FILTER]
    Name    modify
    Match   php.fpm
    Add     log_type php_fpm

[FILTER]
    Name    modify
    Match   mariadb
    Add     log_type mariadb
    
[OUTPUT]
    Name        http
    Match       *
    Host        host.docker.internal
    Port        2021
    URI         /log/ingest
    Format      json